### ISSUE TITLE
Websocket help

### ISSUE THREAD

**Issue by gavin-kelly-1** [EricForgy/Pages.jl#20]
More an issue with my understanding, rather than the codebase.  Trying to get a message from a julia function call that was started by a Pages Post back to the originating browser (prior to the calculation returning the body in a http response, as a form of progress bar):

I've now got the blank.html example working (in chrome, the socket didn't work in firefox 61.0.1, but that might be just me).  And can see the connection in Pages.connections.  I guess if I could get the POST triggered by my javascript to inform the server which client to respond to, I could use Pages.message in julia, but I'm not sure this is the best way, and I can't see a way to access the uid in javascript which I could then append to the POST.

Many thanks for any advice - Gavin

**Comment by EricForgy** [comment]
Hi @macroscian 👋 

The Firefox issue is probably fixed on master of HTTP.jl now with this PR: https://github.com/JuliaWeb/HTTP.jl/pull/321

What you want to do is use `Pages.message` in your loop and include the uid in the POST. 

BUT... like you said, I didn't expose the `id` 😅 

To do that, we just need to add a line here: https://github.com/EricForgy/Pages.jl/blob/master/src/pages.js#L70

Something like 

```js
c = addget(c, "id");
```

and then you can access it via `Pages.id` in your JS code and stick it in your POST.

I'm a little swamped at the moment. If you want to give that a try and if it works maybe you could submit a PR. Otherwise, I'll give it a shot probably early next week.

Edit: This is a one-liner, so I am pushing it to master now 😊

**Comment by EricForgy** [comment]
Hi @macroscian 👋 

Try the master branch and see if that works for you 😊 

You should now be able to access `Pages.id` in your JS code to get the client id and send it with your POST.

Let me know if that helps.

Note that if the user reloads / refreshes the page, the uid will be regenerated. I haven't done anything fancy yet with sessions / cookies. As long as users are aware they cannot reload, e.g. maybe you can add an alert on reload or something, this should be fine I hope.

Let me know how it goes 🙏 

Edit: One quick way to see this is to run the "Blank" example and type `Pages.id` into the dev console 😊

**Comment by gavin-kelly-1** [comment]
Absolutely brilliant - working great now, thanks. Was initially thinking I'd have to hack pages.js to have sock.onmessage call a function with the returned data, but now I see I can get julia to send a "script" message that contains the function call - very clever design.
It's part of a project simulating a cell's response to ultra-violet radiation damage - I'll try to get you acknowledged on the paper, and let you know when it's published.  Thanks for speedy response.

**Comment by EricForgy** [comment]
Awesome! 👏👏👏

Sounds like a cool project. As a sidenote, my PhD was in computational physics and I'd be happy to review your paper and provide feedback (especially if you plan to acknowledge me anyway) 😊 

I was never cutout for academics because I could never get excited about publishing. I have far more acknowledgements in publications than actual publications myself 😅 

PS: I'll go ahead and close this issue as it seems everything is fine now. Don't hesitate to let me know if you run into any other problems 👍
